package com.masim05.bloodpressure.mobile.ui

object TestTags {
    const val AuthModeLogin = "auth_mode_login"
    const val AuthModeNewAccount = "auth_mode_new_account"
    const val AuthError = "auth_error"
    const val GuideScreen = "guide_screen"
    const val CameraScreen = "camera_screen"
    const val CameraPreview = "camera_preview"
    const val CameraLoading = "camera_loading"
    const val CameraError = "camera_error"
    const val CameraOpenSettings = "camera_open_settings"
    const val CameraCapture = "camera_upload"
    const val CameraHistory = "camera_history"
    const val HistoryScreen = "history_screen"
    const val HistoryRefresh = "history_refresh"
    const val HistoryError = "history_error"
    const val HistoryTable = "history_table"
    const val HistoryRow = "history_row"
    const val HistoryFromDate = "history_from"
    const val HistoryToDate = "history_to"
    const val HistoryExportCsv = "history_export_csv"
    const val MeasurementDetailScreen = "measurement_detail_screen"
    const val MeasurementDetailError = "measurement_detail_error"
    const val MeasurementDetailImage = "measurement_detail_image"
    const val MeasurementDetailSystolic = "measurement_detail_systolic"
    const val MeasurementDetailDiastolic = "measurement_detail_diastolic"
    const val MeasurementDetailPulse = "measurement_detail_pulse"
    const val MeasurementDetailArmSide = "measurement_detail_arm_side"
    const val MeasurementDetailSave = "measurement_detail_save"
    const val MeasurementDetailBack = "measurement_detail_back"
    const val BottomNav = "bottom_nav"
    const val BottomNavCapture = "bottom_nav_capture"
    const val BottomNavHistory = "bottom_nav_history"
    const val BottomNavProfile = "bottom_nav_profile"
    const val ProfileScreen = "profile_screen"
    const val ProfileLogout = "profile_logout"
    const val ProfileLanguageSelector = "profile_language_selector"
    const val ProfileGuide = "profile_guide"
    const val ProfileLanguageOptionPrefix = "profile_language_option_"
}
